# Generated by Django 5.1 on 2024-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
                ('OrderDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
