# Generated by Django 5.1 on 2024-08-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvstream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_items',
            fields=[
                ('Line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('ProductName', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Line_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvstream.line_items'),
        ),
    ]
