# Generated by Django 5.1 on 2024-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvstream', '0003_remove_line_items_orderid_remove_order_line_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_items',
            old_name='Line_item_id',
            new_name='LineItemID',
        ),
    ]
